FROM mysql:latest
#COPY . /docker-entrypoint-initdb.d/
# docker run -it -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD=brasil29 -e MYSQL_DATABASE=datingapp chatapp-db
# ENV MYSQL_ROOT_PASSWORD=brasil29
# ENV MYSQL_DATABASE=datingapp
# ENV MYSQL_USER=root
# ENV MYSQL_PASSWORD=brasil29